/**
 * GIS Jobs Berlin — Cloudflare Worker
 *
 * Serves company data as JSON, restricted to your GitHub Pages domain.
 *
 * Deploy: https://dash.cloudflare.com → Workers & Pages → Create Worker → paste this file.
 *
 * SETUP:
 * 1. Replace ALLOWED_ORIGIN with your GitHub Pages URL
 * 2. Deploy → copy the worker URL (*.workers.dev)
 * 3. In index.html set DATA_URL to that worker URL + "/companies"
 *    and replace the hardcoded COMPANIES array with a fetch() call
 */

const ALLOWED_ORIGIN = "https://YOUR_USERNAME.github.io"; // ← change this

const COMPANIES = [
  { id:1, name:"HERE Technologies", lat:52.5313, lng:13.3827, address:"Invalidenstraße 116–119, 10115 Mitte", sector:"Mobility / Mapping", role:"Core product", tech:["FME","ArcGIS","QGIS","Python","SQL","Oracle","PostgreSQL","AWS","Java"], size:"500+", website:"https://here.com", careers:"https://www.here.com/about/careers", linkedin:"https://www.linkedin.com/company/here/", lang:"ENG", about_en:"HERE Technologies is a global leader in mapping and location technology, providing one of the industry's most comprehensive digital map platforms. The company delivers location-based products and services that power navigation, mobility planning, and logistics solutions for automotive manufacturers, enterprises, and software developers worldwide.", about_de:"HERE Technologies ist ein weltweit führendes Unternehmen im Bereich Kartierung und Ortungstechnologie und stellt eine der umfassendsten digitalen Kartenplattformen der Branche bereit. Das Unternehmen bietet standortbasierte Produkte und Dienste für Fahrzeughersteller, Unternehmen und Softwareentwickler weltweit." },
  { id:2, name:"Esri Deutschland", lat:52.5162, lng:13.4056, address:"Karl-Liebknecht-Str. 5, 10178 Mitte", sector:"Tech / GIS", role:"Core product", tech:["ArcGIS","ArcPy","FME","SAP HANA","PostgreSQL","Azure","AWS"], size:"201-500", website:"https://esri.de", careers:"https://www.esri.de/karriere", linkedin:"https://www.linkedin.com/company/esri-deutschland", lang:"DE", about_en:"Esri Deutschland is the exclusive distributor of the ArcGIS platform in Germany and Switzerland. ArcGIS is the world's leading geographic information system, widely used in private industry, government, and academia for spatial analysis, infrastructure planning, and data-driven decision-making.", about_de:"Esri Deutschland ist der exklusive Vertriebspartner der ArcGIS-Plattform von Esri in Deutschland und der Schweiz. ArcGIS ist das weltweit führende Geoinformationssystem und wird in Wirtschaft, Verwaltung und Wissenschaft für räumliche Analysen, Infrastrukturplanung und datengestützte Entscheidungsprozesse eingesetzt." },
  { id:3, name:"Door2Door", lat:52.5281, lng:13.4073, address:"Torstraße 109, 10119 Mitte", sector:"Mobility / Logistics", role:"Core product", tech:["Mapbox","XML","jQuery","Cisco Meraki","Adobe CS"], size:"11-50", website:"https://door2door.io/de/", careers:"https://door2door.io/de/ueber-uns/jobs/", linkedin:"https://www.linkedin.com/company/door2door-mobility/", lang:"ENG/DE", about_en:"Door2Door develops smart on-demand mobility software that closes gaps in public transport networks. By combining flexible routing algorithms with a passenger app, the company enables municipalities and transit operators to run efficient, demand-responsive bus services in areas underserved by conventional fixed-route transit.", about_de:"Door2Door entwickelt intelligente On-Demand-Mobilitätssoftware, die Lücken im öffentlichen Nahverkehr schließt. Durch die Kombination flexibler Routing-Algorithmen mit einer Fahrgast-App ermöglicht das Unternehmen Kommunen und Verkehrsbetrieben, bedarfsgesteuerte Busverbindungen in unterversorgten Gebieten effizient zu betreiben." },
  { id:4, name:"Sweco", lat:52.5174, lng:13.3225, address:"Franklinstraße 28/29, 10587 Charlottenburg", sector:"Urban Planning / Environment", role:"Dedicated team", tech:["ArcGIS","Smallworld","G!nius","SQL","Oracle","PostgreSQL","TypeScript","Kotlin"], size:"500+", website:"https://www.sweco-gmbh.de", careers:"https://www.swecogroup.com/careers/vacancies/", linkedin:"https://www.linkedin.com/company/sweco/", lang:"DE", about_en:"Sweco is a leading European architecture and engineering consultancy working at the core of sustainable urban development. Across infrastructure, water, environment, and energy sectors, Sweco combines design expertise with digital engineering tools to plan and build the cities and communities of the future.", about_de:"Sweco ist ein führendes europäisches Architektur- und Ingenieurbüro, das im Mittelpunkt nachhaltiger Stadtentwicklung steht. In den Bereichen Infrastruktur, Wasser, Umwelt und Energie verbindet Sweco Planungskompetenz mit digitalen Ingenieurwerkzeugen, um die Städte und Gemeinschaften der Zukunft zu gestalten." },
  { id:5, name:"Bettermile", lat:52.4988, lng:13.4228, address:"Oranienstraße 183, 10999 Kreuzberg", sector:"Mobility / Logistics", role:"Core product", tech:["Python","SQL","AWS","Airflow","Dagster","Metabase","Quicksight"], size:"51-200", website:"https://www.bettermile.com", careers:"https://www.bettermile.com/careers/", linkedin:"https://www.linkedin.com/company/bettermile/", lang:"ENG", about_en:"Bettermile provides a geo-driven software platform for last-mile delivery optimization. Its tools for route planning, driver navigation, and tour management help parcel and courier companies improve operational efficiency and deliver a better experience to end customers.", about_de:"Bettermile bietet eine geobasierte Softwareplattform zur Optimierung der letzten Meile in der Paketzustellung. Die Tools für Routenplanung, Fahrer-Navigation und Tourenmanagement helfen Kurier- und Paketdienstleistern, ihre Effizienz zu steigern und Endkunden ein besseres Liefererlebnis zu bieten." },
  { id:6, name:"Toll Collect", lat:52.5065, lng:13.3614, address:"Linkstraße 4, 10785 Tiergarten", sector:"Infrastructure", role:"Dedicated team", tech:["PostgreSQL","PostGIS","ArcGIS Enterprise","QGIS","OSM","Python","GitHub","GitLab"], size:"500+", website:"https://company.toll-collect.de/de", careers:"https://company.toll-collect.de/de/karriere/", linkedin:"https://www.linkedin.com/company/toll-collect-gmbh/", lang:"DE", about_en:"Toll Collect operates Germany's distance-based heavy goods vehicle toll system, one of the most technologically advanced of its kind globally. As a federal technology service provider, the company manages toll collection, enforcement, and a continuously expanding digital services infrastructure for road use across Germany.", about_de:"Toll Collect betreibt das streckenbezogene Lkw-Mautsystem in Deutschland – eines der technologisch fortschrittlichsten seiner Art weltweit. Als bundeseigener Technologiedienstleister verantwortet das Unternehmen Mauterhebung, Kontrolle sowie den kontinuierlichen Ausbau einer digitalen Infrastruktur für die Straßennutzung in Deutschland." },
  { id:7, name:"LiveEO", lat:52.5014, lng:13.4413, address:"Cuvrystraße 3–4, 10997 Kreuzberg", sector:"Environment", role:"Core product", tech:["QGIS","Python","PostGIS","Prefect","Airflow","AWS","Databricks","PyTorch","MLflow"], size:"51-200", website:"https://www.live-eo.com", careers:"https://www.live-eo.com/company/careers", linkedin:"https://www.linkedin.com/company/liveeo/", lang:"ENG", about_en:"LiveEO delivers Earth Observation analytics powered by AI and satellite imagery, enabling organizations to monitor critical infrastructure at scale. Its platform helps asset operators detect risks to power lines, pipelines, and railways, while its supply chain solution supports regulatory compliance with global deforestation legislation.", about_de:"LiveEO liefert KI-gestützte Erdbeobachtungsanalysen auf Basis von Satellitendaten und ermöglicht Organisationen die großflächige Überwachung kritischer Infrastrukturen. Die Plattform unterstützt Asset-Betreiber bei der Früherkennung von Risiken an Stromleitungen, Pipelines und Bahntrassen." },
  { id:8, name:"Planet Labs", lat:52.5051, lng:13.3273, address:"Kurfürstendamm 22, 10719 Charlottenburg", sector:"Environment", role:"Core product", tech:["QGIS","Python","Git","Docker","Jenkins","Linux","ETL","Sentry","Datadog"], size:"500+", website:"https://www.planet.com", careers:"https://www.planet.com/company/careers/", linkedin:"https://www.linkedin.com/company/planet-labs/", lang:"ENG", about_en:"Planet operates the world's largest commercial Earth observation satellite constellation, capturing daily imagery of the entire planet's landmass. Its platform gives governments, businesses, and researchers access to high-frequency, high-resolution geospatial data for environmental monitoring, agricultural analysis, and global change detection.", about_de:"Planet betreibt die weltweit größte kommerzielle Erdbeobachtungs-Satellitenkonstellation und erfasst täglich Bilder der gesamten Landfläche des Planeten. Die Plattform bietet Zugang zu hochfrequenten, hochauflösenden Geodaten für Umweltmonitoring, Landwirtschaftsanalyse und globale Veränderungsdetektion." },
  { id:9, name:"PIX4D", lat:52.5163, lng:13.4071, address:"Münzstraße 19, 10178 Mitte", sector:"Tech / GIS", role:"Core product", tech:["Python","Angular","TypeScript","AWS","Docker","Leaflet","Mapbox","NgRx"], size:"201-500", website:"https://www.pix4d.com", careers:"https://www.pix4d.com/careers/", linkedin:"https://www.linkedin.com/company/pix4d/", lang:"ENG", about_en:"PIX4D is a specialist in drone-based photogrammetry and reality capture software. Its platform enables construction, surveying, and agriculture professionals to process aerial images into precise 2D maps and 3D models, supporting accurate site documentation, measurement workflows, and data-driven project management.", about_de:"PIX4D ist auf drohnenbasierte Photogrammetrie und Reality-Capture-Software spezialisiert. Die Plattform ermöglicht Fachleuten in Bauwesen, Vermessung und Landwirtschaft, Luftbilder in präzise 2D-Karten und 3D-Modelle zu verarbeiten – für genaue Baudokumentation und datengestützte Projektsteuerung." },
  { id:10, name:"CraftingIT", lat:52.4718, lng:13.3358, address:"Hauptstraße 90, 12159 Schöneberg", sector:"Tech / GIS", role:"Dedicated team", tech:["ArcGIS","SQL","ArcGIS Utility Network","Python","VertiGIS Studio"], size:"11-50", website:"https://www.crafting-it.de", careers:"https://www.crafting-it.de/Karriere/Karriere.html", linkedin:"https://www.linkedin.com/company/craftingit/", lang:"DE", about_en:"CraftingIT is an IT services company specializing in GIS application management and long-term system support. As a subsidiary of BridgingIT, it provides outsourcing solutions for organizations relying on the Esri ArcGIS ecosystem, with particular depth in ArcGIS Utility Network implementations for utilities and infrastructure operators.", about_de:"CraftingIT ist ein IT-Dienstleister mit Schwerpunkt auf GIS-Applikationsmanagement und langfristiger Systembetreuung. Als Tochtergesellschaft von BridgingIT bietet das Unternehmen Outsourcing-Lösungen für Organisationen, die das Esri-ArcGIS-Ökosystem nutzen – mit besonderer Tiefe bei ArcGIS Utility Network." },
  { id:11, name:"TRIGIS GeoServices", lat:52.5056, lng:13.4638, address:"Rotherstraße 20, 10245 Friedrichshain", sector:"Infrastructure", role:"Core product", tech:["QGIS","Python","Excel"], size:"201-500", website:"https://www.trigis.de", careers:"https://www.trigis.de/en/karriere", linkedin:"https://www.linkedin.com/company/trigis/", lang:"DE", about_en:"TRIGIS GeoServices provides geodetic surveying, geospatial consulting, and quality assurance services for the infrastructure and construction sectors. The company specializes in precise coordinate measurement, GIS data management, and survey-grade quality monitoring for technically demanding civil engineering projects.", about_de:"TRIGIS GeoServices erbringt geodätische Vermessungsleistungen, geospatiale Beratung und Qualitätssicherung für die Infrastruktur- und Baubranche. Das Unternehmen ist spezialisiert auf präzise Koordinatenmessungen, GIS-Datenverwaltung und vermessungsgenaue Qualitätskontrolle bei anspruchsvollen Bauvorhaben." },
  { id:12, name:"TomTom", lat:52.5225, lng:13.4163, address:"Alexanderstraße 36, 10179 Mitte", sector:"Mobility / Mapping", role:"Core product", tech:["Python","R","SQL","Power BI","Grafana","Tableau"], size:"500+", website:"https://www.tomtom.com", careers:"https://www.tomtom.com/careers/joboverview/", linkedin:"https://www.linkedin.com/company/tomtom/", lang:"ENG", about_en:"TomTom is a global technology company focused on mapping, navigation, and location intelligence. Its Orbis Maps platform delivers a continuously updated, high-definition digital map used by automotive manufacturers, enterprises, and developers for real-time routing, traffic services, and location-based applications worldwide.", about_de:"TomTom ist ein globales Technologieunternehmen mit Fokus auf Kartierung, Navigation und ortsbezogene Intelligenz. Die Orbis Maps-Plattform liefert eine kontinuierlich aktualisierte, hochauflösende digitale Karte – als Grundlage für Echtzeit-Routing, Verkehrsdienste und standortbasierte Anwendungen weltweit." },
  { id:13, name:"MOIA", lat:52.5162, lng:13.3796, address:"Alexanderufer 5, 10117 Mitte", sector:"Mobility", role:"Dedicated team", tech:["SQL","Python","AWS","Azure","GCP"], size:"201-500", website:"https://www.moia.io/de-DE", careers:"https://www.moia.io/de-DE/karriere", linkedin:"https://www.linkedin.com/company/moia_mobility/", lang:"ENG", about_en:"MOIA develops software and services for autonomous and shared urban mobility. As part of the Volkswagen Group, MOIA builds the technology platform that enables on-demand ride-pooling services in cities and prepares public and private transport networks for the integration of autonomous vehicles.", about_de:"MOIA entwickelt Software und Dienste für autonome und geteilte Stadtmobilität. Als Teil des Volkswagen-Konzerns baut MOIA die Technologieplattform, die bedarfsgesteuerte Ridepooling-Dienste in Städten ermöglicht und Verkehrsnetze auf die Integration autonomer Fahrzeuge vorbereitet." },
  { id:14, name:"Berliner Wasserbetriebe", lat:52.5155, lng:13.4113, address:"Neue Jüdenstraße 1, 10179 Mitte", sector:"Infrastructure", role:"Side tool", tech:["Allterra","Leica Geosystems","NavVis"], size:"500+", website:"http://www.bwb.de", careers:"https://www.bwb.de/de/karriere.php", linkedin:"https://www.linkedin.com/company/berliner-wasserbetriebe/", lang:"DE", about_en:"Berliner Wasserbetriebe is Berlin's public utility responsible for drinking water supply and wastewater management. The organization maintains an extensive underground infrastructure network across the city, applying geospatial technologies for network monitoring, infrastructure planning, and operational management of its water and drainage systems.", about_de:"Die Berliner Wasserbetriebe sind das öffentliche Versorgungsunternehmen Berlins und verantwortlich für Trinkwasserversorgung und Abwasserwirtschaft. Das Unternehmen betreibt ein weitverzweigtes unterirdisches Infrastrukturnetz und setzt Geotechnologien für Netzmonitoring, Infrastrukturplanung und den operativen Betrieb ein." },
  { id:15, name:"Deutsche Bahn", lat:52.5100, lng:13.3762, address:"Potsdamer Platz 2, 10785 Tiergarten", sector:"Mobility / Infrastructure", role:"Dedicated team", tech:["PostgreSQL","GeoServer","MapStore","QField","QGIS","Python","JavaScript","React","Docker","AWS"], size:"500+", website:"https://www.deutschebahn.com", careers:"https://db.jobs/de-de", linkedin:"https://www.linkedin.com/company/deutschebahn/", lang:"DE", about_en:"Deutsche Bahn is Germany's national railway operator and one of Europe's largest providers of passenger and freight transport services. The company manages an extensive rail and road network and actively pursues the digital transformation of its infrastructure and operations, including broad use of geospatial data for network planning, maintenance, and asset management.", about_de:"Die Deutsche Bahn ist Deutschlands nationaler Eisenbahnbetreiber und einer der größten Mobilitäts- und Logistikanbieter Europas. Das Unternehmen verwaltet ein weitreichendes Schienen- und Straßennetz und treibt aktiv die digitale Transformation seiner Infrastruktur voran – mit breitem Einsatz von Geodaten für Netzplanung, Instandhaltung und Asset-Management." },
  { id:16, name:"Die Autobahn GmbH", lat:52.5404, lng:13.3649, address:"Heidestraße 15, 10557 Moabit", sector:"Infrastructure / Urban Planning", role:"Dedicated team", tech:["ArcGIS","QGIS","PostGIS","MySQL","GeoServer"], size:"500+", website:"http://www.autobahn.de", careers:"https://www.autobahn.de/karriere/jobportal", linkedin:"https://www.linkedin.com/company/die-autobahn/", lang:"DE", about_en:"Die Autobahn GmbH des Bundes is the federal company responsible for the planning, construction, operation, maintenance, financing, and management of Germany's entire autobahn network. Established through the federal trunk road reform, the company applies geospatial technologies extensively for network monitoring, infrastructure planning, and asset lifecycle management.", about_de:"Die Autobahn GmbH des Bundes ist das bundeseigene Unternehmen, zuständig für Planung, Bau, Betrieb, Erhaltung, Finanzierung und Verwaltung des gesamten deutschen Autobahnnetzes. Das Unternehmen setzt Geoinformationssysteme umfassend für Netzmonitoring, Infrastrukturplanung und Asset-Lebenszyklusmanagement ein." },
  { id:17, name:"Low Carbon", lat:52.5040, lng:13.3296, address:"Knesebeckstraße 32, 10623 Charlottenburg", sector:"Environment / Infrastructure", role:"Dedicated team", tech:["ArcGIS Pro","PostgreSQL","PostGIS"], size:"51-200", website:"https://www.lowcarbon.com/de", careers:"https://www.lowcarbon.com/de/menschen/arbeiten-fuer-low-carbon", linkedin:"https://www.linkedin.com/company/low-carbon/", lang:"ENG", about_en:"Low Carbon is a renewable energy developer focused on large-scale solar, onshore wind, and battery storage projects across the UK and Europe. The company uses geospatial analysis in site selection, environmental assessment, and project planning to identify and develop viable renewable energy locations that support the transition to a low-carbon energy system.", about_de:"Low Carbon ist ein Entwickler erneuerbarer Energien mit Fokus auf großmaßstäbliche Solar-, Wind- und Batteriespeicherprojekte in Großbritannien und Europa. Das Unternehmen nutzt Geoinformationsanalysen bei der Standortauswahl, Umweltbewertung und Projektplanung, um die Energiewende voranzutreiben." },
  { id:18, name:"Accenture", lat:52.4975, lng:13.3870, address:"Hallesches Ufer 40, 10963 Kreuzberg", sector:"Tech / GIS Consulting", role:"Dedicated team", tech:["PostgreSQL","Oracle","Microsoft SQL Server","ArcGIS Pro","ArcGIS Enterprise","Esri Utility Network"], size:"500+", website:"https://www.accenture.com/de-de", careers:"https://www.accenture.com/de-de/careers/jobsearch", linkedin:"https://www.linkedin.com/company/accenture/", lang:"DE", about_en:"Accenture is a global technology and professional services company helping organizations across industries reinvent through digital transformation. Its Berlin team works with utilities, infrastructure operators, and public sector clients on GIS-enabled solutions, with particular focus on ArcGIS Enterprise and Utility Network implementations for network planning and asset management.", about_de:"Accenture ist ein globales Technologie- und Beratungsunternehmen, das Organisationen verschiedener Branchen bei der digitalen Transformation unterstützt. Das Berliner Team arbeitet mit Versorgungsunternehmen, Infrastrukturbetreibern und dem öffentlichen Sektor an GIS-gestützten Lösungen – insbesondere bei ArcGIS Enterprise- und Utility-Network-Implementierungen für Netzplanung und Asset-Management." },
  { id:19, name:"TAUW Deutschland", lat:52.5147, lng:13.4153, address:"Michaelkirchstraße 17–18, 10179 Mitte", sector:"Environment / Urban Planning", role:"Side tool", tech:["ArcGIS","QGIS","GeoDIN","AutoCAD","SQL"], size:"51-200", website:"https://www.tauw.de", careers:"https://www.tauw.de/karriere/stellenangebote/", linkedin:"https://www.linkedin.com/company/tauw-deutschland/", lang:"DE", about_en:"TAUW is a leading European consultancy specializing in environmental consulting, civil engineering, and sustainability. In Germany, TAUW supports industrial, infrastructure, and public sector clients with site investigations, contaminated land management, and geospatial analysis for environmental planning and permitting processes.", about_de:"TAUW ist ein führendes europäisches Beratungs- und Ingenieurbüro mit Schwerpunkt auf Umweltberatung, Bauingenieurwesen und Nachhaltigkeit. In Deutschland unterstützt TAUW Kunden aus Industrie, Infrastruktur und öffentlichem Sektor bei Standortuntersuchungen, Altlastenbearbeitung und räumlicher Analyse für Umweltplanung und Genehmigungsverfahren." },
  { id:20, name:"BWI GmbH", lat:52.4322, lng:13.5329, address:"Rudower Chaussee 13, 12489 Adlershof", sector:"Defense / Infrastructure", role:"Dedicated team", tech:["ArcGIS Pro","ArcGIS Enterprise","Kubernetes"], size:"500+", website:"https://www.bwi.de", careers:"https://www.bwi.de/karriere", linkedin:"https://www.linkedin.com/company/bwi-gmbh/", lang:"DE", about_en:"BWI GmbH is the primary IT service provider for the Bundeswehr (German Armed Forces) and one of Germany's largest IT companies. The company delivers mission-critical IT infrastructure, software solutions, and cybersecurity services, including GIS-based systems used in defense planning and operational support.", about_de:"Die BWI GmbH ist der primäre IT-Dienstleister der Bundeswehr und eines der größten IT-Unternehmen Deutschlands. Das Unternehmen liefert unternehmenskritische IT-Infrastruktur, Softwarelösungen und Cybersicherheitsdienste – darunter GIS-gestützte Systeme für Verteidigungsplanung und Einsatzunterstützung." },
  { id:21, name:"ARC-Greenlab", lat:52.4818, lng:13.4667, address:"Eichenstraße 3b, 12435 Treptow", sector:"Tech / GIS", role:"Core product", tech:["ArcGIS Pro","ArcGIS Enterprise","AWS","Azure","Python","AutoCAD"], size:"51-200", website:"https://www.arc-greenlab.de", careers:"https://karriere.arc-greenlab.de/de", linkedin:"https://www.linkedin.com/company/arc-greenlab-gmbh/", lang:"DE", about_en:"ARC-GREENLAB is an interdisciplinary engineering and software company specializing in geodetic surveying, network documentation, geographic information systems, and Building Information Modelling. The company delivers end-to-end geospatial solutions for utilities, infrastructure operators, and local authorities — from data acquisition through to operational GIS management.", about_de:"ARC-GREENLAB ist ein interdisziplinäres Ingenieur- und Softwareunternehmen, spezialisiert auf Geodäsie, Netzdokumentation, Geoinformationssysteme und Building Information Modelling. Das Unternehmen bietet umfassende Geoinformationslösungen für Versorgungsunternehmen, Infrastrukturbetreiber und Kommunen – von der Datenerfassung bis zum operativen GIS-Betrieb." },
  { id:22, name:"GICON Group", lat:52.5125, lng:13.4190, address:"Wallstraße 14a, 10179 Mitte", sector:"Environment / Infrastructure", role:"Side tool", tech:["ArcGIS Pro","PostgreSQL","PostGIS"], size:"500+", website:"https://www.gicon.de", careers:"https://gicon-gruppe.jobs.personio.de", linkedin:"https://www.linkedin.com/company/gicon-gruppe/", lang:"DE", about_en:"GICON Group is a network of independently operating interdisciplinary engineering companies providing comprehensive services across energy, environment, and infrastructure sectors. The group delivers integrated project planning, environmental consulting, and technical implementation, with geospatial analysis applied across environmental impact assessments and infrastructure projects.", about_de:"Die GICON Group ist ein Verbund eigenständig operierender, interdisziplinärer Ingenieurbüros, die umfassende Ingenieurleistungen in den Bereichen Energie, Umwelt und Infrastruktur anbieten. Die Gruppe deckt integrierte Projektplanung, Umweltberatung und technische Umsetzung ab, wobei räumliche Analysen in Umweltverträglichkeitsprüfungen und Infrastrukturprojekten eingesetzt werden." },
  { id:23, name:"SPIE SAG", lat:52.4310, lng:13.5365, address:"Rudower Chaussee 39, 12489 Adlershof", sector:"Infrastructure / Energy", role:"Side tool", tech:["AutoCAD","BricsCAD","ArcGIS","PostgreSQL","PostGIS"], size:"500+", website:"https://spie.de", careers:"https://spie.de/karriere/stellenangebote", linkedin:"https://www.linkedin.com/company/spie-germany-switzerland-austria/", lang:"DE", about_en:"SPIE SAG is a leading European provider of multi-technical services for energy and communications infrastructure. The company supports clients in designing, building, operating, and maintaining energy-efficient facilities across Germany, applying geospatial tools in network documentation, grid planning, and infrastructure management.", about_de:"SPIE SAG ist ein führender europäischer Anbieter technischer Dienstleistungen für Energie- und Kommunikationsinfrastruktur. Das Unternehmen unterstützt Kunden bei Planung, Bau, Betrieb und Wartung energieeffizienter Anlagen in Deutschland und setzt Geowerkzeuge in der Netzdokumentation, Netzplanung und Infrastrukturverwaltung ein." },
  { id:24, name:"Fichtner", lat:52.5175, lng:13.3210, address:"Franklinstraße 26a, 10587 Charlottenburg", sector:"Environment / Infrastructure", role:"Side tool", tech:["AutoCAD","BricsCAD","ArcGIS","PostgreSQL","PostGIS"], size:"500+", website:"https://www.fichtner.de", careers:"https://www.karriere.fichtner.de", linkedin:"https://www.linkedin.com/company/fichtner/", lang:"DE", about_en:"Fichtner is a leading independent engineering and management consultancy operating internationally across energy, environment, and infrastructure sectors. The company provides project management, technical planning, and feasibility studies for complex engineering projects, with geospatial methods integrated into site assessment and environmental planning.", about_de:"Fichtner ist ein führendes unabhängiges Ingenieur- und Managementberatungsunternehmen, das international in den Bereichen Energie, Umwelt und Infrastruktur tätig ist. Das Unternehmen bietet Projektmanagement, technische Planung und Machbarkeitsstudien für komplexe Ingenieurprojekte an, wobei räumliche Methoden in Standortbewertungs- und Umweltplanungsworkflows integriert sind." },
  { id:25, name:"UP42", lat:52.4945, lng:13.4262, address:"Ohlauer Straße 43, 10999 Kreuzberg", sector:"Tech / GIS", role:"Core product", tech:["Python","Kubernetes","ArcGIS"], size:"51-200", website:"https://up42.com/", careers:"https://up42.com/company/careers", linkedin:"https://www.linkedin.com/company/up42/", lang:"ENG", about_en:"UP42 is a geospatial data and analytics platform aggregating Earth observation data from the world's leading satellite and aerial providers into a single access point. The platform enables organizations across industries to order, process, and analyze geospatial data at scale — supporting use cases from infrastructure monitoring and vegetation management to disaster response.", about_de:"UP42 ist eine Geodaten- und Analyseplattform, die Erdbeobachtungsdaten führender Satelliten- und Luftbildanbieter weltweit an einem einzigen Zugangspunkt bündelt. Die Plattform ermöglicht Organisationen verschiedener Branchen, Geodaten im großen Maßstab zu bestellen, zu verarbeiten und zu analysieren – von Infrastrukturüberwachung und Vegetationsmanagement bis hin zu Katastrophenschutz." },
  { id:26, name:"50Hertz", lat:52.5392, lng:13.3691, address:"Heidestraße 2, 10557 Moabit", sector:"Infrastructure / Energy", role:"Side tool", tech:["ArcGIS"], size:"500+", website:"https://www.50hertz.com", careers:"https://karriere.50hertz.com/search", linkedin:"https://www.linkedin.com/company/50hertz-transmission-gmbh/", lang:"DE", about_en:"50Hertz is one of Germany's four electricity transmission system operators, responsible for the high-voltage grid across northern and eastern Germany. The company manages and expands an extensive transmission network to support the energy transition, applying geospatial systems for network planning, asset management, and grid monitoring.", about_de:"50Hertz ist einer der vier deutschen Übertragungsnetzbetreiber und verantwortlich für das Höchstspannungsnetz in Nord- und Ostdeutschland. Das Unternehmen betreibt und baut ein weitverzweigtes Übertragungsnetz für die Energiewende aus und setzt Geoinformationssysteme für Netzplanung, Asset-Management und Netzüberwachung ein." },
  { id:27, name:"con terra", lat:52.4995, lng:13.3843, address:"Stresemannstraße 123, 10963 Kreuzberg", sector:"Tech / GIS", role:"Core product", tech:["Oracle","PostGIS","Microsoft SQL Server","Python","SQL","JavaScript","FME"], size:"201-500", website:"https://www.conterra.de", careers:"https://www.conterra.de/jobs", linkedin:"https://www.linkedin.com/company/con-terra-gmbh/", lang:"DE", about_en:"con terra is a specialist GIS software and consulting company and Esri Platinum Partner, integrating intelligent geospatial IT solutions into the processes of private enterprises and public authorities. The company develops ArcGIS-based applications and platforms that make geospatial data operationally usable, improving efficiency and transparency across energy, utilities, and public administration.", about_de:"con terra ist ein spezialisiertes GIS-Software- und Beratungsunternehmen und Esri Platinum Partner, das intelligente Geo-IT-Lösungen in die Prozesse von Unternehmen und Behörden integriert. Das Unternehmen entwickelt ArcGIS-basierte Anwendungen und Plattformen, die Geodaten operativ nutzbar machen und Effizienz sowie Transparenz in Energie, Versorgung und öffentlicher Verwaltung steigern." },
  { id:28, name:"Mapbox", lat:52.5370, lng:13.4042, address:"Wolliner Straße 51, 10435 Prenzlauer Berg", sector:"Tech / Mapping", role:"Core product", tech:["Python","NodeJS","TypeScript","Rust","C++","AWS"], size:"500+", website:"https://www.mapbox.com", careers:"https://www.mapbox.com/careers", linkedin:"https://www.linkedin.com/company/mapbox/", lang:"ENG", about_en:"Mapbox is a leading real-time location platform providing the complete toolkit for navigation, mapping, and location intelligence. Its APIs, SDKs, and data services power the navigation of people, packages, and vehicles for organizations worldwide, and its developer platform enables engineers to build custom location-aware applications at any scale.", about_de:"Mapbox ist eine führende Echtzeit-Standortplattform, die das vollständige Werkzeugset für Navigation, Kartierung und ortsbezogene Intelligenz bereitstellt. Seine APIs, SDKs und Datendienste ermöglichen die Navigation von Personen, Paketen und Fahrzeugen für Organisationen weltweit, und die Entwicklerplattform gibt Ingenieuren die Werkzeuge, um benutzerdefinierte standortbezogene Anwendungen in beliebigem Maßstab zu erstellen." },
  { id:29, name:"VertiGIS", lat:52.4822, lng:13.4672, address:"Eichenstraße 3b, 12435 Treptow", sector:"Tech / GIS", role:"Core product", tech:["ArcGIS","QGIS","SQL","PostgreSQL","Python"], size:"500+", website:"https://www.vertigis.com/de/", careers:"https://www.vertigis.com/de/ueber-uns/karriere/", linkedin:"https://www.linkedin.com/company/vertigis/", lang:"DE", about_en:"VertiGIS is a specialist GIS software company developing solutions built on the Esri ArcGIS platform for organizations in energy, water, land management, infrastructure, and public administration. Its products support the full lifecycle of geospatial data management — from planning and asset management through to field operations and reporting.", about_de:"VertiGIS ist ein spezialisiertes GIS-Softwareunternehmen, das auf der Esri-ArcGIS-Plattform aufbauende Lösungen für Organisationen in den Bereichen Energie, Wasser, Landmanagement, Infrastruktur und öffentliche Verwaltung entwickelt. Die Produkte unterstützen den gesamten Lebenszyklus der Geodatenverwaltung – von Planung und Asset-Management bis hin zu Außendienstoperationen und Berichterstattung." },
  { id:30, name:"Eagle Eye Technologies", lat:52.4867, lng:13.3270, address:"Nestorstraße 36a, 10709 Wilmersdorf", sector:"Tech / GIS", role:"Core product", tech:["AutoCAD","QGIS"], size:"11-50", website:"https://www.ee-t.de", careers:"https://www.ee-t.de/jobangebote/", linkedin:"https://www.linkedin.com/company/eagle-eye-technologies-deutschland/", lang:"DE", about_en:"Eagle Eye Technologies is a Berlin-based specialist in mobile mapping, delivering high-precision three-dimensional spatial data for road, railway, and infrastructure surveys. Using measurement vehicles, drones, and aircraft equipped with proprietary sensor systems, the company captures detailed geodata at scale for infrastructure operators, public authorities, and engineering firms across Europe.", about_de:"Eagle Eye Technologies ist ein in Berlin ansässiges Unternehmen, spezialisiert auf Mobile Mapping und die Erfassung hochpräziser dreidimensionaler Raumdaten für Straßen-, Bahn- und Infrastrukturvermessungen. Mit Messfahrzeugen, Drohnen und Flugzeugen, ausgestattet mit eigenentwickelten Sensorsystemen, erfasst das Unternehmen im großen Maßstab Geodaten für Infrastrukturbetreiber, Behörden und Ingenieurbüros in ganz Europa." }
];

// ─── Worker handler ───────────────────────────────────────────────────────────
export default {
  async fetch(request) {
    const origin = request.headers.get("Origin") || "";
    const url = new URL(request.url);

    // Only allow requests from your GitHub Pages domain
    if (origin !== ALLOWED_ORIGIN) {
      return new Response("Forbidden", {
        status: 403,
        headers: { "Content-Type": "text/plain" }
      });
    }

    // Only serve /companies endpoint
    if (url.pathname !== "/companies") {
      return new Response("Not Found", { status: 404 });
    }

    const corsHeaders = {
      "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
      "Access-Control-Allow-Methods": "GET",
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600"
    };

    // Handle CORS preflight
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders });
    }

    return new Response(JSON.stringify(COMPANIES), { headers: corsHeaders });
  }
};
